<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>python3.5 on Zetton's Learning Notes</title><link>https://zEttOn86.github.io/tags/python3.5/</link><description>Recent content in python3.5 on Zetton's Learning Notes</description><generator>Hugo -- gohugo.io</generator><language>ja</language><copyright>2019-2020, zEttOn86 - All rights reserved</copyright><lastBuildDate>Thu, 22 Apr 2021 22:22:22 +0900</lastBuildDate><atom:link href="https://zEttOn86.github.io/tags/python3.5/index.xml" rel="self" type="application/rss+xml"/><item><title>pip実行時にsys.stderr.write(f"ERROR: {exc} ") とエラーが出たときの対処法</title><link>https://zEttOn86.github.io/blog/210422-pip%E5%AE%9F%E8%A1%8C%E6%99%82%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E5%AF%BE%E5%87%A6%E6%B3%95/</link><pubDate>Thu, 22 Apr 2021 22:22:22 +0900</pubDate><guid>https://zEttOn86.github.io/blog/210422-pip%E5%AE%9F%E8%A1%8C%E6%99%82%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E5%AF%BE%E5%87%A6%E6%B3%95/</guid><description>&lt;p>一年に一回は遭遇している気がするのでメモしておきます。&lt;/p></description></item></channel></rss>